#!/bin/bash
# This script builds the Rusty Cryptix WASM32 SDK release.

# make the script fail for any failed command
set -e

rm -rf release/*
rm -rf web/*
rm -rf nodejs/*
rm -rf docs/*
rm -rf examples/nodejs/typescript/lib

mkdir -p release/cryptix-wasm32-sdk/web
mkdir -p release/cryptix-wasm32-sdk/nodejs
mkdir -p release/cryptix-wasm32-sdk/docs

# pushd .
# cd ../rpc/wrpc/wasm
# wasm-pack build --target web --out-name cryptix-rpc --out-dir web/cryptix-rpc --features wasm32-sdk $@
# popd

wasm-pack build --weak-refs --target web --out-name cryptix --out-dir web/cryptix-keygen --features wasm32-keygen $@
wasm-pack build --weak-refs --dev --target web --out-name cryptix --out-dir web/cryptix-keygen-dev --features wasm32-keygen $@

wasm-pack build --weak-refs --target web --out-name cryptix --out-dir web/cryptix-rpc --features wasm32-rpc $@
wasm-pack build --weak-refs --dev --target web --out-name cryptix --out-dir web/cryptix-rpc-dev --features wasm32-rpc $@

wasm-pack build --weak-refs --target web --out-name cryptix --out-dir web/cryptix-core --features wasm32-core $@
wasm-pack build --weak-refs --dev --target web --out-name cryptix --out-dir web/cryptix-core-dev --features wasm32-core $@

wasm-pack build --weak-refs --target web --out-name cryptix --out-dir web/cryptix --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target web --out-name cryptix --out-dir web/cryptix-dev --features wasm32-sdk $@

wasm-pack build --weak-refs --target nodejs --out-name cryptix --out-dir nodejs/cryptix --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target nodejs --out-name cryptix --out-dir nodejs/cryptix-dev --features wasm32-sdk $@
node build/patch-init-warnings.js web nodejs

# wasm-pack build --target web --dev --out-name cryptix --out-dir build/docs/cryptix --features wasm32-sdk $@
typedoc --name "Cryptix WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/cryptix-keygen ./build/docs/cryptix-keygen.ts
typedoc --name "Cryptix WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/cryptix-rpc ./build/docs/cryptix-rpc.ts
typedoc --name "Cryptix WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/cryptix-core ./build/docs/cryptix-core.ts
typedoc --name "Cryptix WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/cryptix ./build/docs/cryptix.ts

# cp -r ../rpc/wrpc/wasm/web/cryptix-rpc release/cryptix-wasm32-sdk/web/cryptix-rpc
cp -r web/cryptix-keygen release/cryptix-wasm32-sdk/web/cryptix-keygen
cp -r web/cryptix-keygen-dev release/cryptix-wasm32-sdk/web/cryptix-keygen-dev

cp -r web/cryptix-rpc release/cryptix-wasm32-sdk/web/cryptix-rpc
cp -r web/cryptix-rpc-dev release/cryptix-wasm32-sdk/web/cryptix-rpc-dev

cp -r web/cryptix-core release/cryptix-wasm32-sdk/web/cryptix-core
cp -r web/cryptix-core-dev release/cryptix-wasm32-sdk/web/cryptix-core-dev

cp -r web/cryptix release/cryptix-wasm32-sdk/web/cryptix
cp -r web/cryptix-dev release/cryptix-wasm32-sdk/web/cryptix-dev

cp -r nodejs/cryptix release/cryptix-wasm32-sdk/nodejs/cryptix
cp -r nodejs/cryptix-dev release/cryptix-wasm32-sdk/nodejs/cryptix-dev

cp -r docs/cryptix-keygen release/cryptix-wasm32-sdk/docs/cryptix-keygen
cp -r docs/cryptix-rpc release/cryptix-wasm32-sdk/docs/cryptix-rpc
cp -r docs/cryptix-core release/cryptix-wasm32-sdk/docs/cryptix-core
cp -r docs/cryptix release/cryptix-wasm32-sdk/docs/cryptix

mkdir -p release/cryptix-wasm32-sdk/examples/data
cp -r examples/data/.gitignore release/cryptix-wasm32-sdk/examples/data/.gitignore
cp -r examples/nodejs release/cryptix-wasm32-sdk/examples/
cp -r examples/web release/cryptix-wasm32-sdk/examples/
cp -r examples/init.js release/cryptix-wasm32-sdk/examples/
cp -r examples/jsconfig.json release/cryptix-wasm32-sdk/examples/
cp -r examples/package.json release/cryptix-wasm32-sdk/examples/

pushd .
cd release/cryptix-wasm32-sdk/examples
npm install
popd

# tsc release/cryptix-wasm32-sdk/examples/nodejs/typescript/

cp index.html release/cryptix-wasm32-sdk/index.html
cp README.md release/cryptix-wasm32-sdk/README.md
cp CHANGELOG.md release/cryptix-wasm32-sdk/CHANGELOG.md
cp LICENSE release/cryptix-wasm32-sdk/LICENSE

node build/package-sizes.js
cp package-sizes.js release/cryptix-wasm32-sdk/package-sizes.js

pushd .
cd release
zip -q -r cryptix-wasm32-sdk.zip cryptix-wasm32-sdk
popd
